<?php


namespace app\controllers;

use app\models\Blog;
use Yii;
class MarketingController extends baseController
{
    public $layout = 'marketing';
    public $navItems = ['blog' => 'Блог', 'reviews' => 'Отзывы',
                        'comparison' => 'Сравнение', 'algorithm' =>
                        'Алгоритм', 'business' => 'Бизнесс', ];

    public function actionIndex()
    {
        $this->modalFormSending();
        $this->view->title = 'Главная страница';
        \Yii::$app->getView()->params['standardHeader'] = false;
        return $this->render('index'); // TODO: Change the autogenerated stub
    }

    public function actionBlog($length = 4)
    {
        $this->modalFormSending();
        $this->view->title = 'Блог';
        $blogs = Blog::find()->limit($length)->all();
        \Yii::$app->getView()->params['standardHeader'] = true;
        return $this->render('blog', ['blogs' => $blogs, 'length' => $length]);
    }

    public function actionArticle($id = 1)
    {
        $this->modalFormSending();
        $article = Blog::find()->where(['id' => $id])->one();
        $this->view->title = 'Статья';
        \Yii::$app->getView()->params['standardHeader'] = true;
        return $this->render('Article', [
            'article' => $article
        ]);
    }
}